// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfGdySp063oZRDNT_y9Qregrkv8gdaPq8',
    appId: '1:854228304119:web:308f69825eead91e5913f2',
    messagingSenderId: '854228304119',
    projectId: 'cityco-7f8d7',
    authDomain: 'cityco-7f8d7.firebaseapp.com',
    storageBucket: 'cityco-7f8d7.appspot.com',
    measurementId: 'G-6QN7K2WW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKLywE5ug7CcVWC0WQ79GGfsoh7pIScE',
    appId: '1:854228304119:android:569f7c31f7dd51e25913f2',
    messagingSenderId: '854228304119',
    projectId: 'cityco-7f8d7',
    storageBucket: 'cityco-7f8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99XmM5rR7HLcfMvvSr0g5cwTQsJqHApI',
    appId: '1:854228304119:ios:eab43d42b38b3f085913f2',
    messagingSenderId: '854228304119',
    projectId: 'cityco-7f8d7',
    storageBucket: 'cityco-7f8d7.appspot.com',
    androidClientId: '854228304119-4il24rqurs6qr59jpfuh70dhulk9k5h4.apps.googleusercontent.com',
    iosClientId: '854228304119-h5faf5vf5jgro93veie53k52a7cvulf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99XmM5rR7HLcfMvvSr0g5cwTQsJqHApI',
    appId: '1:854228304119:ios:4a4240e8f48421435913f2',
    messagingSenderId: '854228304119',
    projectId: 'cityco-7f8d7',
    storageBucket: 'cityco-7f8d7.appspot.com',
    androidClientId: '854228304119-4il24rqurs6qr59jpfuh70dhulk9k5h4.apps.googleusercontent.com',
    iosClientId: '854228304119-lof3qfmskn4puvnth5nmdif28nolcaj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityco.RunnerTests',
  );
}
